development:
  adapter: postgresql
  database: eventdark_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: eventdark_test
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: eventdark_staging
  pool: 5
  timeout: 5000